[package]
authors = ["CrazyMerlyn <crazy.d.merlyn@gmail.com>"]
name = "termchess"
version = "0.1.0"

[dependencies]
env_logger = "0.4.0"
lazy_static = "0.2.2"
pgn-reader = "0.4.0"
shakmaty = "0.6.1"
uci = "0.1.1"
